# Generated by Django 3.2 on 2021-11-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211030_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان نمایشی')),
                ('slug', models.CharField(max_length=255, verbose_name='عنوان لاتین')),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.ManyToManyField(related_name='specialty', to='account.specialty', verbose_name='تخصص ها'),
        ),
    ]
